language: php
php:
- 7.1
- 7.2
- 7.3
services:
- mysql
sudo: false
env:
  global:
  - DEPENDENCIES=standard
  - TRAVIS_TEST_EXCLUDES="--exclude-group slow,jpgraph,pushserver"
  - secure: Ph/EBYyRlBNDt4JJX58vRPswodJwNP1iTj+b/X6R4WjpWqo0O5JYkw7KzgXutVWSJuk/A9v1lg9SVrXcMdn/553JfZU0h1M+rGsHuVGBIkk9cmTlxrT78cDkI/Hk/0PINgdIOYE1UniRvWF5EGPIIrTjtKB4s/MCv/CXJokZ058=
  - secure: PrhfXk0WZqxcgMc+xp/mkTpdvZseXblF/MRu6MDlkD8tn9iQKEHM1Xy/dCIo2IHI40gEd/tr6imbBuPn06npINWyV1np6rmRWUNBuiano5khYkxZHPlVwKeXmnyCm4w5oZEHf8EzyJtK2R+8TFGzEUU/SjjWocZffkgf3oUn2aU=
  matrix:
  - DB=mysql
matrix:
  include:
  - php: 7.1
    services: postresql
    env: DB=pgsql
  - php: 7.1
    env: DB=sqlite
  - php: 7.1
    env: DB=mysql COMPONENT=HTTPD
  - php: 7.1
    env: DB=mysql COMPONENT=PUSHD
  - php: 7.1
    env: DB=mysql COMPONENT=DOCKER
  - php: 7.1
    env: DB=mysql DEPENDENCIES=lowest
  - php: 7.1
    env: DB= DEPENDENCIES= JSLINT=true
cache:
  directories:
  - "$COMPOSER_CACHE_DIR"
  - "$HOME/.composer/cache"
  - node_modules
before_install:
- if [ -e /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  ]; then rm /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini;
  fi
install:
- if [ "$JSLINT" = true ]; then npm install -g gulp; npm install; fi
- if [ "$DEPENDENCIES" = "standard" ]; then composer install; fi
- if [ "$DEPENDENCIES" = "lowest" ]; then composer update --prefer-lowest -n; fi
- |
  if [ "$JSLINT" != true ]; then
    phpenv config-add ./test/bin/apc.ini && printf "\n" | pecl install apcu
    php -r 'echo(function_exists("apcu_store")?"APCu enabled":"APCu disabled");'
  fi
before_script:
- set -e
- cp etc/volkszaehler.conf.template.php etc/volkszaehler.conf.php
- DATABASE=volkszaehler
- USER=root
- PASSWORD=
- if [ "$DB" = "pgsql" ]; then USER=postgres; fi
- sed -i "s/'pdo_mysql'/'pdo_$DB'/" etc/volkszaehler.conf.php
- sed -i "s/'vz'/'$USER'/" etc/volkszaehler.conf.php
- sed -i "s/'demo'/'$PASSWORD'/" etc/volkszaehler.conf.php
- sed -i "s/'volkszaehler'/'$DATABASE'/" etc/volkszaehler.conf.php
- sed -i "s/'secretkey'/'secretkey' =\> '08154711', \/\//" etc/volkszaehler.conf.php
- sed -i "s/\/\/ 'user'/'user'/" etc/volkszaehler.conf.php
- if [ "$DB" = "sqlite" ]; then sed -i "s/\?>/\$config['db']['path']\ =\ VZ_DIR.'\/sqlite.db3'\;\n?>/"
  etc/volkszaehler.conf.php; fi
- cat etc/volkszaehler.conf.php
- if [ "$DB" = "mysql" ]; then mysql -e "CREATE DATABASE $DATABASE;" -u $USER; fi
- if [ "$DB" = "pgsql" ]; then psql -c "CREATE DATABASE $DATABASE;" -U $USER; fi
- if [ -n "$DB" ]; then php bin/doctrine orm:schema-tool:create; fi
- |
  if [ "$COMPONENT" = "HTTPD" ]; then
    sed -i "s/testAdapter\" value=\".*\"/testAdapter\" value=\"HTTP\"/" phpunit.xml
    vendor/bin/ppm start -c etc/middleware.json &
  fi
- |
  if [ "$COMPONENT" = "PUSHD" ]; then
    sed -i "s/\?>/\$config['push']['enabled']\ =\ true\;\n?>/" etc/volkszaehler.conf.php
    php bin/push-server &
  fi
after_script:
- |
  if [ "$COMPONENT" = "HTTPD" ]; then
    vendor/bin/ppm stop -c etc/middleware.json
  fi
script:
- if [ -n "$DB" ]; then vendor/bin/phpunit $TRAVIS_TEST_EXCLUDES,aggregation; fi
- |
  if [ "$DB" = "mysql" ]; then
    sed -i "s/\?>/\$config['aggregation']\ =\ true;\n?>/" etc/volkszaehler.conf.php
    php bin/aggregate run -m delta -l hour
    vendor/bin/phpunit $TRAVIS_TEST_EXCLUDES
  fi
- if [ "$COMPONENT" = "PUSHD" ]; then vendor/bin/phpunit --group pushserver; fi
- if [ "$JSLINT" = true ]; then gulp jshint; fi
after_success:
- echo $COMPONENT
- echo $TRAVIS_BRANCH
- echo $DOCKER_USER
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=andig/volkszaehler
- docker pull $REPO:latest
- docker build --cache-from $REPO:latest -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:latest
- docker push $REPO
