# general settings overriding php configuration
php:
  timezone: Europe/Berlin
  locale: ['de_DE', 'en_US', 'C']

# Doctrine database configuration
# http://www.doctrine-project.org/projects/doctrine-dbal/en/2.6
db:
  driver: pdo_mysql
  host: 127.0.0.1
  port: 3306
  user: vz
  password: demo
  charset: utf8
  dbname: volkszaehler
  path: volkszaehler # only used for sqlite

  # db admin credentials (used by doctrine cli and setup script)
  admin:
    user: vz_admin
    password: admin_demo

  # database optimizer - leave empty for automatic
  # optimizer: Volkszaehler\Interpreter\SQL\MySQLOptimizer # provides additional group=15m setting for demo purposes

# push server for realtime frontend updates
push:
  server: 5582
  broadcast: 8082
  # routes for wamp access
  wamp:
    - /
    - /ws
  # routes for plain web socket access
  websocket:
    - /socket

security:
  # limit maximum POST body size, e.g. 4096
  maxbodysize: false
  # local machines to trust as (reverse) proxy
  proxies: ['127.0.0.1/8', '::1', '192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8', 'fe80::/64']

# Access control
# Define firewall rules per ip, path or method and actions 'allow', 'deny' and 'auth'
firewall:
  # localhost
  - ips: ['127.0.0.1/8', '::1']
    action: allow
  # local network
  - ips: ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8', 'fe80::/64']
    action: allow
  # always allow /auth - this is required
  - path: /auth
    methods: POST
    action: allow
  # authorize all other requests
  - action: auth

# User authorization for firewall rule action 'auth'
# NOTE: if using authorization *ALWAYS* make sure HTTPS is enforced
authorization:
  secretkey:    # define your own random secret key
  valid: 86400  # token validity period in seconds

# User configuration
users:
  # add users below as user: password
  plain:
    user: password
  # add user constraints below as understood by bin/token-helper.php
  # empty context/operation array means no constraints
  constraints:
    # user:
    #   context: [ array of allowed contexts ]
    #   operation: [ array of allowed operations ]

# enable debug messages by default if true
debug: false
